data()
df<-print(cars)

setwd("/Users/anbun/Documents/r_programming_exercise")
data<- read.csv("employee.csv")
print(data)
print(is.data.frame(data))
print(ncol(data))
print(nrow(data))
#to get max salary
salary<-max(data$Salary)
print(salary)
max_salary_details <- subset(data,Salary==max(Salary))
print(max_salary_details)
details_It_dep <- subset(data,Department=="IT")
print(details_It_dep)
#to write in csv
write.csv(details_It_dep,"output.csv")
newdata<- read.csv("output.csv")
print(newdata)
write.csv(details_It_dep,"output.csv",row.names = FALSE)
newdata<-read.csv("output.csv")
print(newdata)
install.packages("xlsx")
any(grepl("xlsx",installed.packages()))
library("xlsx")
